server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: Phong@123
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  kafka:
    topic: user.events
  user-service:
    url: http://localhost:8081
